Models/Concert.cs
namespace Final_Project.Models
{
    public class Concert
    {
        public int ConcertId { get; set; }
        public string Artist { get; set; }
        public string Venue { get; set; }
        public int Year { get; set; }
        public int Rating { get; set; }
    }
}

Models/ConcertContext.cs
/*using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace Final_Project.Models
{
    public class ConcertContext : DbContext
    {
        public DbSet<Concert> Concerts { get; set; }
    }
}
*/

Models/ErrorViewModel.cs
namespace Final_Project.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Student.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Final_Project.Models
{
    public class Student
    {
        public int StudentId { get; set; }
        public string Name { get; set; }
        public string Major { get; set; }
        public string Concentration { get; set; }
        public int Year { get; set; }
        public string FavoriteFood { get; set; }
        public string FavoriteSong { get; set; }
        public string Hometown { get; set; }
    }
}

Models/StudentContext.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace Final_Project.Models
{
    public class StudentContext : DbContext
    {
        public DbSet<Student> Students { get; set; }
    }
}

Controllers/HobbieController.cs
using Final_Project.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Final_Project.Controllers
{
    public class HobbieController : Controller
    {
        private readonly ILogger<HobbieController> _logger;

        public HobbieController(ILogger<HobbieController> logger)
        {
            _logger = logger;
        }
        public IActionResult Hobbie1()
        {
            return View();
        }

        public IActionResult Hobbie2()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/HomeController.cs
using Final_Project.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Final_Project.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
                
        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult Home()
        {
            return View();
        }

        public IActionResult Charlie()
        {
            return View();
        }

        public IActionResult Vedant()
        {
            return View();
        }
        public IActionResult Francesca()
        {
            return View();
        }        

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/StudentController.cs
using Final_Project.Models;
using Microsoft.AspNetCore.Mvc;

namespace Final_Project.Controllers
{
    public class StudentController : Controller
    {
        private StudentContext context;

        public StudentController(StudentContext ctx) { context = ctx;  }
        public IActionResult Index()
        {
            // return RedirectToAction("List", "Product");
            return View();
        }

        [Route("[controller]s/{StudentId?}")]
        public IActionResult List(string StudentId = "All")
        {
            var students = context.Students
                .OrderBy(c => c.StudentId).ToList();

            ViewBag.Students = students;

            // bind products to view
            return View(students);
        }

       /* public IActionResult Details(int StudentId)
        {
            var students = context.Students
                .OrderBy(c => c.StudentId).ToList();

            Student student = context.Students.Find(StudentId);

            // string imageFilename = product.Code + "_m.png";

            // use ViewBag to pass data to view
            ViewBag.Students = students;
            //ViewBag.ImageFilename = imageFilename;

            // bind product to view
            return View(student);
        }*/

    }
}

Views/Hobbie/Hobbie1.cshtml
@{
    ViewData["Title"] = "Small Concerts";
}

<style>
    table, th, td {
        border: 1px solid black;
        padding: 3px;
    }
</style>

<h1>Small Concerts We Have Attended</h1>

<table>
    <tr>
        <th>Venue</th>
        <th>Artist</th>
        <th>Year</th>
    </tr>
    <tr>
        <td>Aragon Ballroom</td>
        <td>Joji</td>
        <td>2022</td>
    </tr>
    <tr>
        <td>KEMBA! Live</td>
        <td>The 1975</td>
        <td>2016</td>
    </tr>
    <tr>
        <td>Grand Ol Opry House</td>
        <td>Lorde</td>
        <td>2022</td>
    </tr>
</table>

Views/Hobbie/Hobbie2.cshtml
@{
    ViewData["Title"] = "Large Concerts";
}

<style>
    table, th, td {
        border: 1px solid black;
        padding: 3px;
    }
</style>

<h1>Large Concerts We Have Attended</h1>

<table>
    <tr>
        <th>Venue</th>
        <th>Artist</th>
        <th>Year</th>
    </tr>
    <tr>
        <td>Madison Square Garden</td>
        <td>Harry Styles</td>
        <td>2022</td>
    </tr>
    <tr>
        <td>Schottenstein Center</td>
        <td>AJR</td>
        <td>2022</td>
    </tr>
    <tr>
        <td>United Center</td>
        <td>Harry Styles</td>
        <td>2022</td>
    </tr>
</table>

Views/Home/Charlie.cshtml
@{
    ViewData["Title"] = "Charlie";
}

<html lang="en">
	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		<link rel="shortcut icon" href="images/favicon.png">
		<link rel="stylesheet" type="text/css" href="styles/style.css">
		<title>Personal Page</title>
	</head>
	<body>		
		<main>
			<div class="mainContent">
					<div class="card-container">					
						<div class="upper-container">
						</div>			
						<div class="lower-container">
							<div class="name">Charlie Phelps</div>
							<div class="profession">Information Technology - Softwawre Development</div>
							<div class="divider"></div>
							<div class="bio">4th Year Student at the University of Cincinnati. </div>
						</div>
					</div>
				<div class="box-text">
					<p></p>
					<p>Work Experience: Cincinnati Financial</p>

					<ul type="disc">
						<li>Programming languages: <strong>Java, Python, C++, TypeScript, SQL </strong></li>
					</ul>

					<p>What I'm interested in:</p>

					<ul type="disc">
						<li><strong>Gaming</strong></li>
						<li><strong>Math</strong></li>
						<li><strong>Reading</strong></li>
						<li><strong>Hiking</strong></li>
						<li><strong>Biking</strong></li>
					</ul>

			</div>
			</div>
		</main>
	
	</body>
</html>

Views/Home/Francesca.cshtml
@{
    ViewData["Title"] = "Francesca";
}



<html lang="en">
	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		<link rel="shortcut icon" href="images/favicon.png">
		<link rel="stylesheet" type="text/css" href="styles/style.css">
		<title>Personal Page</title>
	</head>
	<body>		
		<main>
			<div class="mainContent">
				<div class="card-container">					
					<div class="upper-container">
					</div>			
					<div class="lower-container">
						<div class="name">Francesca Suba</div>
						<div class="profession">BS/MS in Information Technology</div>
						<div class="divider"></div>
						<div class="bio">4th Year IT student interested in Software Development, Project Management, and UI/UX Design</div>
					</div>		

				</div>
				<div class="box-text">				
					<p>I have completed all three of my co-ops at 84.51.</p>	
					
						<ul type="disc">
							<li>Programming languages: <strong>Python, HTML/CSS, Java, JavaScript</strong></li>
							<li>Operating Systems: <strong>Microsoft Windows, Linux, MacOS, Android, IOS</strong></li>
						</ul>
					
					<p>What I'm interested in:</p>
					
						<ul type="disc">
							<li><strong>Concerts</strong></li>
							<li><strong>Cooking</strong></li>
							<li><strong>Traveling</strong></li>
						</ul>
					
				</div>
			</div>
		</main>
	
	</body>
</html>

Views/Home/Home.cshtml
@model List<Student>
@{
    ViewData["Title"] = "Home";
}

<h1>Home</h1>
<table class="table table-bordered table-striped">
    <thead>
        <tr><th>StudentId</th><th>Name</th><th>Major</th><th>Concentration</th><th>Year</th><th>FavoriteFood</th><th>FavoriteSong</th>
        <th>Hometown</th></tr>
    </thead>
    @*<tbody>
        @foreach (Student student in Model)
        {
            <tr>
                <td>@student.StudentId</td>
                <td>@student.Name</td>
                <td>@student.Major</td>
                <td>@student.Concentration</td>
                <td>@student.Year</td>
                <td>@student.FavoriteFood</td>
                <td>@student.FavoriteSong</td>
                <td>@student.Hometown</td>
            </tr>
        }
    </tbody>*@
</table>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>WEB SERVER APPLICATION DEV (001) Final project By: Vedant Amin, Francesca Suba, Charles Phelps.</p>
</div>

Views/Home/Vedant.cshtml
@{
    ViewData["Title"] = "Vedant";
}



<html lang="en">
	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		<link rel="shortcut icon" href="images/favicon.png">
		<link rel="stylesheet" type="text/css" href="styles/style.css">
		<title>Personal Page</title>
	</head>
	<body>		
		<main>
			<div class="mainContent">
				<div class="card-container">					
					<div class="upper-container">
					</div>			
					<div class="lower-container">
						<div class="name">Vedant Amin</div>
						<div class="profession">Information technology Major</div>
						<div class="divider"></div>
						<div class="bio">Full time Student at the University of Cincinnati. </div>
					</div>		

				</div>
				<div class="box-text">				
					<p>My past Work Experience includes Apple Inc, Parker hannafin, Ascena Inc, and Merck.  </p>	
					
						<ul type="disc">
							<li>Programming languages: <strong>Python, C/C++, HTML, Java, JavaScript, SQL </strong></li>
							<li>Networks: <strong>Configuration, Servers, Routers, LAN Technology </strong></li>
							<li>Operating Systems: <strong>Microsoft Windows, Linux, Unix, MacOS, Android, IOS</strong></li>
						</ul>
					
					<p>What I'm interested in:</p>
					
						<ul type="disc">
							<li><strong>CryptoCurrency</strong></li>
							<li><strong>Blockchain</strong></li>
							<li><strong>Quant</strong></li>
						</ul>
					
				</div>
			</div>
		</main>
	
	</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Final Project</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Final_Project.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Final Project</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Home">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Charlie">Charlie</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Vedant">Vedant</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Francesca">Francesca</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Hobbie" asp-action="Hobbie1">Small Concerts</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Hobbie" asp-action="Hobbie2">Large Concerts</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>